data<- read.table("household_power_consumption.txt", sep=";", header=TRUE)
data$Date<- as.Date(data$Date, "%d/%m/%Y")
newData<- subset(data, Date>="2007-02-01" & Date<="2007-02-02")
hist(as.numeric(as.character(newData$Global_active_power)), xlab="Global Active Power (kilowatts)", main="Global Active Power", col="Red")
dev.copy(png, file="plot1.png", width=480, height=480)
dev.off()