data<- read.table("household_power_consumption.txt", sep=";", header=TRUE)
data$Date1<- as.Date(data$Date, "%d/%m/%Y")
newData<- subset(data, Date1>="2007-02-01" & Date1<="2007-02-02")
newData$DateTime<- paste(newData$Date,  newData$Time, sep=",")
newData$DateTime<- strptime(newData$DateTime, format="%d/%m/%Y, %H:%M:%S")
par(mfrow=c(2,2))
x<- newData$DateTime
y<- as.numeric(as.character(newData$Global_active_power))
plot(x,y,ylab="Global Active Power", xlab="", cex=0)
lines(x,y)
volt<- as.numeric(as.character(newData$Voltage))
plot(x,volt, ylab="Voltage", xlab="datetime", cex=0)
lines(x,volt)
y1<- as.numeric(as.character(newData$Sub_metering_1))
y2<- as.numeric(as.character(newData$Sub_metering_2))
y3<- as.numeric(as.character(newData$Sub_metering_3))
with(newData, plot(x,y1, cex=0), plot(x,y2,cex=0), plot(x,y3,cex=0), xlab="", ylab="Energy sub metering")
lines(x,y1); lines(x,y3,col="blue"); lines(x,y2,col="red")
legend("topright", lty=c(1,1,1), col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n")
y4<-as.numeric(as.character(newData$Global_reactive_power))
plot(x,y4,cex=0, xlab="datetime", ylab="Global_reactive_power")
lines(x,y4)
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()